# Site settings
title: El
title1: objeto
description: "Análisis y Crítica"
url: "https://pebeto.github.io/"
author:
  name: "Jose Esparza"
  email_address: "joseesparza@tutanota.com"
  github_profile: "https://github.com/pebeto"
  twitter_profile: "https://twitter.com/pebeto99"
  linkedin_profile: "https://linkedin.com/in/josesparza"

emerald: 
  site: "https://github.com/KingFelix/emerald"
  author: "https://github.com/KingFelix"

# Build settings
baseurl: /
markdwon: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate

# Options
reverse: false
